kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc
spec:
  volumeMode: FileSystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gold
      