kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <VALUE_MANE>
spec:
  # volumeMode: <VALUE_VOLUME_MODE> # Optional. values FileSystem\Block. The default is FileSystem.
  storageClassName: <VALUE_STORAGE_CLASS_NAME>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <STORAGE_SIZE_VALUE>
